# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  name "bifrost"
  desc "Session context bridge between AI coding tools"
  homepage "https://github.com/kogungor/bifrost"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost"

  on_macos do
    on_intel do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_darwin_amd64.tar.gz"
      sha256 "cad1370979ea6cc765784cd3fe4b6b649c921ed9500a5cbe50e180fca65dc539"
    end
    on_arm do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_darwin_arm64.tar.gz"
      sha256 "046ec94496b02fb091d53e0e85c944fbf771e2c3eb573d570cc0eeff8fb72617"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_linux_amd64.tar.gz"
      sha256 "ac0df7e8279d3b9ebf7a938ca2d7d5c6996b40652aa31b8c8870181612119f74"
    end
    on_arm do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_linux_arm64.tar.gz"
      sha256 "a68372ed68de75956ea8822bafec0e88b18a616555e7e18d4494d77eb20ac795"
    end
  end

  # No zap stanza required
end
