# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  name "bifrost"
  desc "Session context bridge between AI coding tools"
  homepage "https://github.com/kogungor/bifrost"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost"

  on_macos do
    on_intel do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_darwin_amd64.tar.gz"
      sha256 "506da7753465dddac07b5dd98d2e4adcc5af7026c42015237eaee474c81a1ce4"
    end
    on_arm do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_darwin_arm64.tar.gz"
      sha256 "c8cd4ac8cc1241480f745e32ba2f75cb6f7b3b4eecee47777f0a782357c8fde6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_linux_amd64.tar.gz"
      sha256 "37ae909e535cdb9be9709d38cfcc97938fc955979be6cb00fb80a0e344727746"
    end
    on_arm do
      url "https://github.com/kogungor/bifrost/releases/download/v#{version}/bifrost_linux_arm64.tar.gz"
      sha256 "2c355c3570d63cc63aff170a032bacaca85cfd729341ade084cea7c8d9153ee9"
    end
  end

  # No zap stanza required
end
